obj-m += keycounter.o 

all:
	# make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
	make -C /home/askrey/STUDENT/Linux/vroot/lib/modules/6.7.4/build M=$(PWD) modules
clean:
	# make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
	make -C /home/askrey/STUDENT/Linux/vroot/lib/modules/6.7.4/build M=$(PWD) clean
